### ISSUE TITLE
modal window doesn't close when click outside

### ISSUE THREAD

**Issue by aerdemsenturk** [mikedoubintchik/wordpress-post-modal#16]
Hi, I was using v 3.5.2. After update to 3.6.0, modal window doesn't close when I click outside of the modal. In Chrome everything is fine but with Firefox 79.0 I get this error:

Uncaught TypeError: e.originalEvent.path is undefined
    <anonymous> https://....com/wp-content/plugins/wp-post-modal/public/js/wp-post-modal-public.js:172
    jQuery 2
        dispatch
        handle

**Comment by mikedoubintchik** [comment]
Fixed in 3.6.1
