### ISSUE TITLE
Modal-link triggers all Bootstrap modal windows in the page.

### ISSUE THREAD

**Issue by aerdemsenturk** [mikedoubintchik/wordpress-post-modal#17]
I'm using several bootstrap modal window in my page. When I click a "modal-link" classed link, opens all modal window along with "wp-post-modal" window. 

I think wordpress-post-modal could have a different css class name than bootstrap. When I change class name to ".modal2", in class-wp-post-modal-public.php and wp-post-modal-public.css,  it works well with other bootstrap modals.

**Comment by mikedoubintchik** [comment]
@aerdemsenturk Great point. I've updated this in [v3.6.2](https://github.com/mikedoubintchik/wordpress-post-modal/releases/tag/3.6.2)

`.modal` is now `.wp-post-modal`
