### ISSUE TITLE
modal displays but browser still loads new page

### ISSUE THREAD

**Issue by SunfireWeb** [mikedoubintchik/wordpress-post-modal#19]
I really like this plugin, and have not had this issue on any other sites I've used it before. But I'm working with a different theme and there must be some conflict I can't narrow down and isolate.

I'm using a footer script to add class="modal-link" to a certain set of anchor tags. This part works. The links now open in a modal as expected.

But for some reason, the page ALSO reverts to the standard, loading the page in the link.

I've tried things like setting stopPropagation() and preventDefault() for the <a> onClick events, but that seems to only cancel the modal, not the page load.

The site is https://msba125thanniversary.mars-cdn.com/
WordPress 5.8
theme: Tower v 2.9.21 (by codeless http://www.codeless.co/)
plugin version 3.6.3

I'm applying the "modal-link" class to a tags in the Timeline and the Testimonials.

Any suggestions you might have would be appreciated. Thanks.

**Comment by mikedoubintchik** [comment]
@SunfireWeb Are you still having this issue? I went to your site and didn't see the modal-link class.

**Comment by SunfireWeb** [comment]
Interestingly, I ran updates to both Header Footer Code Manager (used to add the script) and the Tower theme. After re-enabling the script for the testimonial links, it appears to be working as expected now, no page redirect behind the popup.
Would you mind checking for me, and see if you are seeing this as well?
Specifically, the "Read More" link of the Testimonials.

**Comment by SunfireWeb** [comment]
Tested site in various browsers, all working as expected.

**Comment by mikedoubintchik** [comment]
Yep, working as expected for me as well!
