### ISSUE TITLE
Since New 3.7.0 Update, I have HTML displaying at the bottom of my website

### ISSUE THREAD

**Issue by 121940kz** [mikedoubintchik/wordpress-post-modal#20]
https://www.mindikcounts.com/

at the bottom of every page it is displaying this in plain text

`<div class="modal-wrapper styled" role="dialog" aria-modal="true" aria-label="Popup Dialog"><div class="wp-post-modal"><button type="button" aria-label="Close" class="close-modal"> × </button><div id="modal-content"></div></div></div>`

Something appears to be accidentally broken in your new version, it also has happened on another completely separate site https://siloswellnesscenter.com

Also after updating, your modal dialogs in the admin are also displaying plain text html

```
<h4>Thanks for installing WP Post Popup!</h4><p>Please <a href="https://wordpress.org/support/plugin/wp-post-modal/reviews/" target="_blank">click here</a> to give us a review :)</p>Dismiss this notice.

<div id="modal-ready"><h5>WP Post Popup</h5> <p>I will start offering an option to <a href="https://allurewebsolutions.com/product/wp-post-popup-support">purchase 6 month of support</a> for $30. I will no longer field questions that are sent by email or in the wordpress.org forums. I hope that everyone will do their part in supporting this open source project.</p> </div>
```

Please advise.

**Comment by mikedoubintchik** [comment]
Thank you for this. I've fixed it.

Please reinstall version 3.7.0
